# Generated by Django 2.2.4 on 2019-09-10 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_item_discount_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='discription',
            field=models.TextField(default='This is a test product description.jldsjljoei owslsakdlroe dlkoajroe '),
            preserve_default=False,
        ),
    ]
