# Generated by Django 2.2.4 on 2019-09-11 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20190911_1353'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='item',
            new_name='items',
        ),
    ]
